# Abstract {.unnumbered}

**Dynamics of the Southern Hemisphere zonally asymmetric circulation**

This thesis' objective is to describe and improve our understanding of the zonally asymmetric circulation in the Southern Hemisphere in seasonal and longer timescales.
To that end, we used ERA5 data, Coupled Model Intercomparison Project Phase 6 (CMIP6) historical simulations and Detection and Attribution Model Intercomparison Project (DAMIP) sensibility experiments.
We computed the Complex Empirical Orthogonal Functions (cEOFs) of the 200 hPa and 50 hPa geopotental height zonal anomalies, which enabled us to characterise the amplitude and phase of the main variability patterns of the zonally asymmetric circulation.

Two main modes of variability were identified.
The first cEOF (cEOF1) represents the zonal wave 1 variability in the stratosphere and is associated with a Southern Annular mode (SAM) like pattern in the troposphere and significant stratospheric ozone anomalies.
Its 0º phase has a positive trend in the 1940--2020 period, consistent with the evolution of the ozone hole.
On the other hand, the second cEOF (cEOF2) represents a wave 3 pattern with maximum amplitude in the Pacific region mainly in the troposphere with a weaker signal in the stratosphere.
This mode is related to Pacific-South American mode (PSA) like spatial patterns and an SAM-like annular pattern.
Its impact on surface-level temperature and precipitation anomalies depends on its phase.
Although this mode is active in the absence of tropical forcing, tropical Pacific sea surface temperature anomalies do influence its phase.

We separated the SAM into its zonally symmetric (S-SAM) and asymmetric (A-SAM) parts.
The S-SAM is associated with an zonally symmetric annular pattern, whereas the A-SAM is associated with a zonal wave 3-4.
The correlation between El Niño-Southern Oscillation and SAM is due solely to the latter's asymmetric component, while the SAM index positive trend is only present in its symmetric component.
Regional impacts of each component are also distinct and correspond to distinct processes.

By studying the relationship between both SAM components and the main modes of variability we concluded that the cEOF1 is moderately related with the A-SAM, mainly in its 90º phase in the stratosphere.
The cEOF2 90º phase is highly correlated with the A-SAM in the troposphere, which indicates that these two indices are describing the same physical phenomenon.
This further suggest that the A-SAM might not be a physical mode and that it should be instead be understood as a phase of the cEOF2 (PSA) and it appears as part of the SAM due to the methods used to isolate it.

Finally, we studied these modes in CMIP6 historical simulations and found that they can represent them relatively well, although model ability varies widely.
The multimodel mean does represent them satisfactorily.
However, most models overestimate the relationship between these modes and sea surface temperatures.
Exploration of the external forcings which could explain the cEOF1 trend we found that the increase in greenhouse gasses forces a negative trend in the cEOF1 0º phase, while the change in stratospheric ozone forces a positive trend.
Both effects partially compensate to explain the almost null trend in the historical experiments.
For the 90º phase, both greenhouse gasses and stratospheric ozone force a negative trend, while stratospheric aerosols force a positive trend.
The balance of these forcings results a a negative trend.
