# Agradecimientos {.unnumbered}

A mis directores, Carolina y Leandro, quienes luego de sufrirme durante una tesis de licenciatura, decidieron pasar otros 6 años guiando esta tesis de doctorado. 
¡Prometo que esta es la última!

Al CONICET por darme de comer durante el doctorado, a la FCEN y el DCAO por ofrecer la educación de calidad que me permite investigar, y al CIMA por darme un lugar de trabajo y recursos para hacer lo que amo hacer. 

A la comunidad de R, en cuyos amplios y cómodos hombros me paro para escribir esta tesis de forma abierta y reproducible. 

A mi familia.
Clementina y David, cuyas contribuciones al sentarse sobre el teclado fueron imprescindibles. 
Mis suegres, que me cebaron mate y trajeron bananas mientras escribía esta tésis. 
Mi papá, que un día me sentó en una plaza de San Juan para hablarme de la gravitación.
Enrique, que me mostró la maleabilidad del plomo.
Goyo, que me ayudó a aprender a leer con la "J" de "joder".
Y mi mamá, con quién compartimos largas discusiones sobre cómo hacer ciencia y escribir papers; extraño no poder brindar con ella para celebrar cada acontecimiento importante. 

A Pao, la mejor compañera de trabajo y de vida.  
